### ISSUE TITLE
How does this compare to tbastos' vim-lua?

### ISSUE THREAD

**Issue by alerque** [3uclidian/BetterLua.vim#1]
I'm been using [tbastos/vim-lua](https://github.com/tbastos/vim-lua) for ages now and have even suggested that most of the fixes there should be upstreamed. I saw this recommended and now I'm wondering how they compare, which makes sense to adapt to going forward, etc. Any comments?

cf. Similar [issue raised in reverse](https://github.com/tbastos/vim-lua/issues/20).

**Comment by euclidianAce** [comment]
Taking a quick glance, it doesn't look like that plugin (currently) supports the new 5.4 `<attribute>` syntax and mine allows changing the highlights of the standard library based on the `g:lua_subversion`. It also looks like the doc comments are a little different and this is specific to EmmyLua which requires a triple dash `---` to use.

But other than that they seem kinda similar. I'd recommend just trying out both and seeing if there's one you prefer or a certain feature that you need.
